name: Actions Workflow

on:
  repository_dispatch:
    types:
      - 'on-demand-test'
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "closed"
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: List Files
        run: |
          pwd
          ls -a
